import { Recipe } from "@/types/recipe";

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Mediterranean Quinoa Bowl",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    category: "Healthy",
    time: "30 min",
    vegetables: ["Tomatoes", "Cucumber", "Bell Peppers", "Red Onion", "Olives"],
    ingredients: [
      { name: "Quinoa", amount: "1 cup" },
      { name: "Cherry tomatoes", amount: "1 cup, halved" },
      { name: "Cucumber", amount: "1 medium, diced" },
      { name: "Bell peppers", amount: "2, diced" },
      { name: "Red onion", amount: "1/2, thinly sliced" },
      { name: "Kalamata olives", amount: "1/2 cup, pitted" },
      { name: "Feta cheese", amount: "1/2 cup, crumbled" },
      { name: "Olive oil", amount: "3 tbsp" },
      { name: "Lemon juice", amount: "2 tbsp" },
      { name: "Fresh herbs", amount: "2 tbsp, chopped" },
    ],
    procedure: [
      "Cook quinoa according to package instructions and let cool.",
      "Dice the cucumber and bell peppers into bite-sized pieces.",
      "Thinly slice the red onion and halve the cherry tomatoes.",
      "In a large bowl, combine cooked quinoa with all vegetables.",
      "Add olives and crumbled feta cheese.",
      "Whisk together olive oil, lemon juice, and herbs for dressing.",
      "Drizzle dressing over the bowl and toss gently to combine.",
      "Season with salt and pepper to taste. Serve chilled or at room temperature.",
    ],
  },
  {
    id: 2,
    title: "Herb-Crusted Salmon",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    category: "Seafood",
    time: "25 min",
    vegetables: ["Asparagus", "Lemon", "Herbs"],
  },
  {
    id: 3,
    title: "Roasted Vegetable Medley",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    category: "Vegetarian",
    time: "40 min",
    vegetables: [
      "Zucchini",
      "Bell Peppers",
      "Carrots",
      "Broccoli",
      "Cauliflower",
    ],
  },
  {
    id: 4,
    title: "Classic Beef Steak",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
    category: "Meat",
    time: "45 min",
    meats: ["Beef"],
    vegetables: ["Potatoes", "Green Beans"],
    ingredients: [
      { name: "Ribeye steak", amount: "2 steaks, 1 inch thick" },
      { name: "Potatoes", amount: "4 medium, cubed" },
      { name: "Green beans", amount: "1 lb, trimmed" },
      { name: "Butter", amount: "3 tbsp" },
      { name: "Garlic", amount: "4 cloves, minced" },
      { name: "Rosemary", amount: "2 sprigs" },
      { name: "Salt", amount: "to taste" },
      { name: "Black pepper", amount: "to taste" },
      { name: "Olive oil", amount: "2 tbsp" },
    ],
    procedure: [
      "Remove steaks from refrigerator 30 minutes before cooking to bring to room temperature.",
      "Preheat oven to 400°F. Toss potatoes with olive oil, salt, and pepper. Roast for 25-30 minutes until golden.",
      "Season steaks generously with salt and pepper on both sides.",
      "Heat a cast-iron skillet over high heat. Add 1 tbsp butter and sear steaks for 3-4 minutes per side for medium-rare.",
      "Add remaining butter, garlic, and rosemary to the pan. Baste steaks with the butter mixture.",
      "Remove steaks and let rest for 5-10 minutes before slicing.",
      "Steam or blanch green beans until tender-crisp, about 4-5 minutes.",
      "Serve steaks with roasted potatoes and green beans, drizzled with pan juices.",
    ],
  },
  {
    id: 5,
    title: "Creamy Mushroom Risotto",
    image:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    category: "Vegetarian",
    time: "35 min",
    vegetables: ["Mushrooms", "Onion", "Garlic"],
  },
  {
    id: 6,
    title: "Grilled Chicken Salad",
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    category: "Healthy",
    time: "20 min",
    meats: ["Chicken"],
    vegetables: ["Lettuce", "Tomatoes", "Cucumber", "Red Onion"],
    ingredients: [
      { name: "Chicken breast", amount: "2 pieces, boneless" },
      { name: "Mixed greens", amount: "6 cups" },
      { name: "Cherry tomatoes", amount: "1 cup, halved" },
      { name: "Cucumber", amount: "1 medium, sliced" },
      { name: "Red onion", amount: "1/4, thinly sliced" },
      { name: "Olive oil", amount: "2 tbsp" },
      { name: "Lemon juice", amount: "2 tbsp" },
      { name: "Dijon mustard", amount: "1 tsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Black pepper", amount: "to taste" },
    ],
    procedure: [
      "Season chicken breasts with salt, pepper, and 1 tbsp olive oil.",
      "Heat grill or grill pan over medium-high heat. Grill chicken for 6-7 minutes per side until cooked through.",
      "Let chicken rest for 5 minutes, then slice into strips.",
      "In a large bowl, combine mixed greens, tomatoes, cucumber, and red onion.",
      "Whisk together remaining olive oil, lemon juice, Dijon mustard, salt, and pepper for the dressing.",
      "Toss salad with half the dressing, then top with sliced grilled chicken.",
      "Drizzle remaining dressing over the chicken. Serve immediately.",
    ],
  },
  {
    id: 7,
    title: "Pasta Carbonara",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    category: "Italian",
    time: "25 min",
    meats: ["Bacon", "Pancetta"],
    ingredients: [
      { name: "Spaghetti", amount: "1 lb" },
      { name: "Pancetta", amount: "8 oz, diced" },
      { name: "Eggs", amount: "4 large" },
      { name: "Parmesan cheese", amount: "1 cup, grated" },
      { name: "Black pepper", amount: "1 tsp, freshly ground" },
      { name: "Garlic", amount: "2 cloves, minced" },
      { name: "Salt", amount: "to taste" },
    ],
    procedure: [
      "Bring a large pot of salted water to boil. Cook spaghetti according to package directions until al dente.",
      "While pasta cooks, heat a large skillet over medium heat. Add diced pancetta and cook until crispy, about 8-10 minutes.",
      "In a bowl, whisk together eggs, grated Parmesan, and black pepper. Set aside.",
      "Reserve 1 cup of pasta water before draining. Drain pasta and immediately add to the skillet with pancetta.",
      "Remove skillet from heat. Quickly toss hot pasta with pancetta, then add the egg mixture, stirring constantly.",
      "Add reserved pasta water a little at a time until sauce is creamy and coats the pasta.",
      "Season with salt and additional pepper if needed. Serve immediately with extra Parmesan on top.",
    ],
  },
  {
    id: 8,
    title: "Thai Green Curry",
    image:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    category: "Asian",
    time: "30 min",
    meats: ["Chicken"],
    vegetables: ["Bell Peppers", "Eggplant", "Thai Basil"],
  },
  {
    id: 9,
    title: "Chocolate Lava Cake",
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80",
    category: "Dessert",
    time: "20 min",
    locked: true,
    ingredients: [
      { name: "Dark chocolate", amount: "6 oz, chopped" },
      { name: "Butter", amount: "6 tbsp" },
      { name: "Eggs", amount: "2 large" },
      { name: "Egg yolks", amount: "2" },
      { name: "Sugar", amount: "1/4 cup" },
      { name: "All-purpose flour", amount: "2 tbsp" },
      { name: "Vanilla extract", amount: "1 tsp" },
      { name: "Salt", amount: "pinch" },
      { name: "Powdered sugar", amount: "for dusting" },
    ],
    procedure: [
      "Preheat oven to 425°F. Butter and flour 4 ramekins.",
      "Melt chocolate and butter in a double boiler or microwave, stirring until smooth. Let cool slightly.",
      "In a separate bowl, whisk together eggs, egg yolks, and sugar until pale and thick.",
      "Gradually whisk the melted chocolate mixture into the egg mixture.",
      "Fold in flour, vanilla extract, and salt until just combined.",
      "Divide batter evenly among prepared ramekins.",
      "Bake for 12-14 minutes until edges are set but center is still soft.",
      "Let cool for 1 minute, then invert onto plates. Dust with powdered sugar and serve immediately.",
    ],
  },
  {
    id: 10,
    title: "Fresh Sushi Platter",
    image:
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    category: "Seafood",
    time: "60 min",
    vegetables: ["Cucumber", "Avocado", "Carrots"],
  },
  {
    id: 11,
    title: "Vegetable Stir Fry",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    category: "Vegetarian",
    time: "15 min",
    vegetables: [
      "Broccoli",
      "Carrots",
      "Bell Peppers",
      "Snow Peas",
      "Mushrooms",
    ],
  },
  {
    id: 12,
    title: "BBQ Ribs",
    image:
      "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=800&q=80",
    category: "Meat",
    time: "120 min",
    meats: ["Pork"],
    vegetables: ["Corn", "Coleslaw"],
  },
  {
    id: 13,
    title: "Margherita Pizza",
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    category: "Italian",
    time: "30 min",
    vegetables: ["Tomatoes", "Basil"],
    ingredients: [
      { name: "Pizza dough", amount: "1 lb" },
      { name: "Tomato sauce", amount: "1/2 cup" },
      { name: "Fresh mozzarella", amount: "8 oz, sliced" },
      { name: "Fresh basil", amount: "1/2 cup, leaves" },
      { name: "Olive oil", amount: "2 tbsp" },
      { name: "Garlic", amount: "2 cloves, minced" },
      { name: "Salt", amount: "to taste" },
      { name: "Black pepper", amount: "to taste" },
    ],
    procedure: [
      "Preheat oven to 475°F with a pizza stone or baking sheet inside.",
      "Roll out pizza dough on a floured surface to desired thickness.",
      "Mix tomato sauce with minced garlic, salt, and pepper.",
      "Spread sauce evenly over the dough, leaving a border for the crust.",
      "Arrange mozzarella slices over the sauce.",
      "Drizzle with olive oil and season with salt and pepper.",
      "Bake for 12-15 minutes until crust is golden and cheese is bubbly.",
      "Remove from oven, top with fresh basil leaves, and serve immediately.",
    ],
  },
  {
    id: 14,
    title: "Chicken Tikka Masala",
    image:
      "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80",
    category: "Asian",
    time: "45 min",
    meats: ["Chicken"],
    vegetables: ["Onion", "Tomatoes", "Bell Peppers"],
  },
  {
    id: 15,
    title: "Caesar Salad",
    image:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
    category: "Healthy",
    time: "15 min",
    meats: ["Chicken"],
    vegetables: ["Romaine Lettuce", "Parmesan"],
  },
  {
    id: 16,
    title: "Beef Tacos",
    image:
      "https://images.unsplash.com/photo-1565299585323-38174c0c0c0e?w=800&q=80",
    category: "Meat",
    time: "25 min",
    meats: ["Beef"],
    vegetables: ["Lettuce", "Tomatoes", "Onion", "Cilantro"],
  },
  {
    id: 17,
    title: "Vegetable Lasagna",
    image:
      "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80",
    category: "Vegetarian",
    time: "60 min",
    vegetables: ["Zucchini", "Eggplant", "Spinach", "Mushrooms", "Tomatoes"],
  },
  {
    id: 18,
    title: "Lobster Bisque",
    image:
      "https://images.unsplash.com/photo-1547573854-74d2a71d0826?w=800&q=80",
    category: "Seafood",
    time: "50 min",
    vegetables: ["Onion", "Carrots", "Celery", "Tomatoes"],
    locked: true,
  },
  {
    id: 19,
    title: "Tiramisu",
    image:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80",
    category: "Dessert",
    time: "30 min",
  },
  {
    id: 20,
    title: "Pad Thai",
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&q=80",
    category: "Asian",
    time: "20 min",
    meats: ["Chicken", "Shrimp"],
    vegetables: ["Bean Sprouts", "Carrots", "Green Onions"],
    ingredients: [
      { name: "Rice noodles", amount: "8 oz" },
      { name: "Chicken breast", amount: "1, sliced" },
      { name: "Shrimp", amount: "8 oz, peeled" },
      { name: "Bean sprouts", amount: "1 cup" },
      { name: "Carrots", amount: "2, julienned" },
      { name: "Green onions", amount: "3, chopped" },
      { name: "Eggs", amount: "2, beaten" },
      { name: "Fish sauce", amount: "3 tbsp" },
      { name: "Tamarind paste", amount: "2 tbsp" },
      { name: "Brown sugar", amount: "2 tbsp" },
      { name: "Lime juice", amount: "2 tbsp" },
      { name: "Peanuts", amount: "1/4 cup, crushed" },
    ],
    procedure: [
      "Soak rice noodles in warm water for 20 minutes until pliable. Drain and set aside.",
      "Mix fish sauce, tamarind paste, brown sugar, and lime juice to make the sauce.",
      "Heat a large wok or skillet over high heat. Add oil and cook chicken until done, then add shrimp and cook until pink.",
      "Push meat to one side, add beaten eggs and scramble.",
      "Add drained noodles and sauce. Toss everything together for 2-3 minutes.",
      "Add bean sprouts, carrots, and most of the green onions. Toss for 1 more minute.",
      "Serve hot, garnished with remaining green onions and crushed peanuts.",
    ],
  },
  {
    id: 21,
    title: "Greek Moussaka",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80",
    category: "Meat",
    time: "90 min",
    meats: ["Lamb", "Beef"],
    vegetables: ["Eggplant", "Potatoes", "Tomatoes", "Onion"],
    locked: true,
  },
  {
    id: 22,
    title: "Avocado Toast",
    image:
      "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
    category: "Healthy",
    time: "10 min",
    vegetables: ["Avocado", "Tomatoes", "Red Onion"],
  },
  {
    id: 23,
    title: "Eggplant Parmesan",
    image:
      "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=800&q=80",
    category: "Vegetarian",
    time: "45 min",
    vegetables: ["Eggplant", "Tomatoes", "Basil"],
  },
  {
    id: 24,
    title: "Shrimp Scampi",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80",
    category: "Seafood",
    time: "20 min",
    vegetables: ["Garlic", "Lemon", "Parsley"],
  },
  {
    id: 25,
    title: "Chicken Parmesan",
    image:
      "https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=800&q=80",
    category: "Italian",
    time: "40 min",
    meats: ["Chicken"],
    vegetables: ["Tomatoes", "Basil"],
  },
  {
    id: 26,
    title: "Beef Bulgogi",
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561b1e?w=800&q=80",
    category: "Asian",
    time: "35 min",
    meats: ["Beef"],
    vegetables: ["Onion", "Carrots", "Green Onions"],
  },
  {
    id: 27,
    title: "Fruit Parfait",
    image:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    category: "Healthy",
    time: "10 min",
  },
  {
    id: 28,
    title: "Stuffed Bell Peppers",
    image:
      "https://images.unsplash.com/photo-1615367423057-4b46b8a18103?w=800&q=80",
    category: "Vegetarian",
    time: "50 min",
    vegetables: ["Bell Peppers", "Tomatoes", "Onion", "Rice"],
  },
  {
    id: 29,
    title: "Grilled Tuna Steak",
    image:
      "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=800&q=80",
    category: "Seafood",
    time: "15 min",
    vegetables: ["Asparagus", "Lemon"],
  },
  {
    id: 30,
    title: "Beef Wellington",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
    category: "Meat",
    time: "150 min",
    meats: ["Beef"],
    vegetables: ["Mushrooms", "Onion"],
    locked: true,
  },
  {
    id: 31,
    title: "Panna Cotta",
    image:
      "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
    category: "Dessert",
    time: "25 min",
  },
  {
    id: 32,
    title: "Spaghetti Aglio e Olio",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    category: "Italian",
    time: "15 min",
    vegetables: ["Garlic", "Parsley", "Red Pepper"],
  },
  {
    id: 33,
    title: "Chicken Teriyaki",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80",
    category: "Asian",
    time: "30 min",
    meats: ["Chicken"],
    vegetables: ["Broccoli", "Carrots", "Green Onions"],
  },
  {
    id: 34,
    title: "Kale Smoothie Bowl",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    category: "Healthy",
    time: "10 min",
    vegetables: ["Kale", "Spinach"],
  },
  {
    id: 35,
    title: "Mushroom Stroganoff",
    image:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    category: "Vegetarian",
    time: "35 min",
    vegetables: ["Mushrooms", "Onion", "Garlic"],
  },
  {
    id: 36,
    title: "Crab Cakes",
    image:
      "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=800&q=80",
    category: "Seafood",
    time: "30 min",
    vegetables: ["Bell Peppers", "Onion", "Celery"],
  },
  {
    id: 37,
    title: "Lamb Chops",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
    category: "Meat",
    time: "25 min",
    meats: ["Lamb"],
    vegetables: ["Mint", "Garlic", "Rosemary"],
  },
  {
    id: 38,
    title: "Cheesecake",
    image:
      "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800&q=80",
    category: "Dessert",
    time: "60 min",
  },
  {
    id: 39,
    title: "Risotto ai Funghi",
    image:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    category: "Italian",
    time: "40 min",
    vegetables: ["Mushrooms", "Onion", "Garlic", "Parmesan"],
  },
  {
    id: 40,
    title: "Ramen Bowl",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    category: "Asian",
    time: "35 min",
    meats: ["Pork"],
    vegetables: ["Green Onions", "Mushrooms", "Seaweed", "Egg"],
  },
  {
    id: 41,
    title: "Quinoa Power Bowl",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    category: "Healthy",
    time: "25 min",
    vegetables: ["Kale", "Sweet Potatoes", "Avocado", "Tomatoes"],
  },
  {
    id: 42,
    title: "Zucchini Noodles",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    category: "Vegetarian",
    time: "20 min",
    vegetables: ["Zucchini", "Tomatoes", "Basil", "Garlic"],
  },
  {
    id: 43,
    title: "Seafood Paella",
    image:
      "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=800&q=80",
    category: "Seafood",
    time: "50 min",
    vegetables: ["Bell Peppers", "Tomatoes", "Peas", "Onion"],
    locked: true,
  },
  {
    id: 44,
    title: "Pork Tenderloin",
    image:
      "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=800&q=80",
    category: "Meat",
    time: "40 min",
    meats: ["Pork"],
    vegetables: ["Apples", "Onion", "Potatoes"],
  },
  {
    id: 45,
    title: "Chocolate Soufflé",
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80",
    category: "Dessert",
    time: "30 min",
  },
  {
    id: 46,
    title: "Fettuccine Alfredo",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    category: "Italian",
    time: "25 min",
    meats: ["Chicken"],
    vegetables: ["Broccoli"],
  },
  {
    id: 47,
    title: "Korean Bibimbap",
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561b1e?w=800&q=80",
    category: "Asian",
    time: "40 min",
    meats: ["Beef"],
    vegetables: ["Carrots", "Spinach", "Bean Sprouts", "Cucumber"],
  },
  {
    id: 48,
    title: "Acai Bowl",
    image:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    category: "Healthy",
    time: "5 min",
  },
];
